run tests:
  stage: test
  image: python:3.9.18
  script:
    - cp .env.example .env
    - pip install -r requirements-dev.txt
    - pytest --cov --cov-report term --cov-report xml:coverage.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
